name: PR Source Check
on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check the source branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only the ‘dev’ branch can be merged into ‘main’"
            exit 1
          fi
